name: Client
on:
  push:
    branches:
      - main
    paths:
      - 'packages/client/**'
  pull_request:
    branches:
      - main
    paths:
      - 'packages/client/**'

jobs:
  check:
    name: Typecheck client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: bahmutov/npm-install@v1
      - name: Typecheck
        uses: gozala/typescript-error-reporter-action@v1.0.8
        with:
          project: packages/client/tsconfig.json

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14, 16]
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - uses: bahmutov/npm-install@v1
      - name: Test (ES)
        run: yarn --cwd packages/client test:es
      - name: Test (Web)
        run: yarn --cwd packages/client test:web
      - name: Test (CJS)
        run: yarn --cwd packages/client test:cjs
      - name: Coverage
        run: yarn --cwd packages/client coverage
